import java.awt.Frame;
import javax.swing.*;

public class Korea extends JFrame {
Details test = new Details();
String id,email;
Frame_UI asdf = new Frame_UI();
    public Korea() {
                setUndecorated(true);
        initComponents();
        setSize(1600,900); //resize me someday
        setExtendedState(Frame.MAXIMIZED_BOTH);
	setLocationRelativeTo(null);
        setTitle("You are exploring Korea");
        setBounds(new java.awt.Rectangle(0,0,1600,900));         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Prev = new javax.swing.JButton();
        Button_Home = new javax.swing.JButton();
        Button_Next = new javax.swing.JButton();
        Button_Stand1 = new javax.swing.JButton();
        Button_Stand2 = new javax.swing.JButton();
        Button_Stand3 = new javax.swing.JButton();
        Button_Stand5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Button_Prev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Import_Insider/E-Week-ThaiPrev.png"))); // NOI18N
        Button_Prev.setBorder(BorderFactory.createEmptyBorder());
        Button_Prev.setContentAreaFilled(false);
        Button_Prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PrevActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Prev);
        Button_Prev.setBounds(0, 810, 340, 90);

        Button_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Import_Insider/homeicon.png"))); // NOI18N
        Button_Home.setBorder(BorderFactory.createEmptyBorder());
        Button_Home.setContentAreaFilled(false);
        Button_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_HomeActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Home);
        Button_Home.setBounds(730, 770, 130, 130);

        Button_Next.setBorder(BorderFactory.createEmptyBorder());
        Button_Next.setContentAreaFilled(false);
        Button_Next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Import_Insider/E-Week-JapanNext.PNG"))); // NOI18N
        Button_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_NextActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Next);
        Button_Next.setBounds(1350, 820, 250, 80);

        Button_Stand1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Import_Insider/btn_detail.png"))); // NOI18N
        Button_Stand1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Stand1.setBorder(BorderFactory.createEmptyBorder());
        Button_Stand1.setContentAreaFilled(false);
        Button_Stand1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Stand1ActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Stand1);
        Button_Stand1.setBounds(60, 330, 210, 70);

        Button_Stand2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Import_Insider/btn_detail.png"))); // NOI18N
        Button_Stand2.setBorderPainted(false);
        Button_Stand2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Stand2.setBorder(BorderFactory.createEmptyBorder());
        Button_Stand2.setContentAreaFilled(false);
        Button_Stand2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Stand2ActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Stand2);
        Button_Stand2.setBounds(730, 320, 210, 60);

        Button_Stand3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Import_Insider/btn_detail.png"))); // NOI18N
        Button_Stand3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Stand3.setBorder(BorderFactory.createEmptyBorder());
        Button_Stand3.setContentAreaFilled(false);
        Button_Stand3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Stand3ActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Stand3);
        Button_Stand3.setBounds(1160, 510, 210, 70);

        Button_Stand5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Import_Insider/btn_detail.png"))); // NOI18N
        Button_Stand5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Stand5.setBorder(BorderFactory.createEmptyBorder());
        Button_Stand5.setContentAreaFilled(false);
        Button_Stand5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Stand5ActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Stand5);
        Button_Stand5.setBounds(390, 500, 210, 70);

        jLabel2.setFont(new java.awt.Font("TeXGyreAdventor", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Junett 21");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(780, 290, 160, 40);

        jLabel3.setFont(new java.awt.Font("TeXGyreAdventor", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Moo Moo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 300, 160, 40);

        jLabel4.setFont(new java.awt.Font("TeXGyreAdventor", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Omo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(440, 470, 130, 40);

        jLabel5.setFont(new java.awt.Font("TeXGyreAdventor", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setText("Kimbap Nara");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1200, 480, 130, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Import_Insider/Backgroud/Korea_sth.PNG"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 1610, 940);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_HomeActionPerformed
  
        asdf.id = id;
        asdf.email = email;
        asdf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button_HomeActionPerformed

    private void Button_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_NextActionPerformed
         Japan zxc = new Japan();
         zxc.id = id;
         zxc.email = email;
         zxc.setVisible(true);   //japan
      
        this.dispose();
    }//GEN-LAST:event_Button_NextActionPerformed

    private void Button_PrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PrevActionPerformed
         Thailand zxc = new Thailand();
         zxc.id = id;
         zxc.email = email;
         zxc.setVisible(true);
       setVisible(false);
    }//GEN-LAST:event_Button_PrevActionPerformed

    private void Button_Stand1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Stand1ActionPerformed
        test.getSaus("13"); //moomoo
        test.id = id;
        test.email = email;
        test.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button_Stand1ActionPerformed

    private void Button_Stand2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Stand2ActionPerformed
        test.getSaus("14"); //junett
        test.id = id;
        test.email = email;
        test.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_Button_Stand2ActionPerformed

    private void Button_Stand3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Stand3ActionPerformed
        test.getSaus("16"); //omo
        test.id = id;
        test.email = email;
        test.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button_Stand3ActionPerformed

    private void Button_Stand5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Stand5ActionPerformed
        test.getSaus("15");

       test.id = id;
       test.email = email;
       test.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button_Stand5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Korea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Korea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Korea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Korea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Korea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Home;
    private javax.swing.JButton Button_Next;
    private javax.swing.JButton Button_Prev;
    private javax.swing.JButton Button_Stand1;
    private javax.swing.JButton Button_Stand2;
    private javax.swing.JButton Button_Stand3;
    private javax.swing.JButton Button_Stand5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
